# Generated by Django 4.2.6 on 2023-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_game_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wrongGuesses',
            field=models.IntegerField(default=0),
        ),
    ]
